### ISSUE TITLE
Empty Config File

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/tool-dapploy-nodejs#8]
Observed: An empty config file results in a parse error
Expected: Run with default settings

Running dapploy
 $ Parsing config dapploy.conf
Error: Bad Config File
    at configParsing (/Users/arietrouw/GitHub/tool-dapploy-nodejs/src/configParser.js:37:11)
    at parseConfig (/Users/arietrouw/GitHub/tool-dapploy-nodejs/src/configParser.js:67:3)
    at dapploy (/Users/arietrouw/GitHub/tool-dapploy-nodejs/src/deployDapp.js:46:5)
    at p (/Users/arietrouw/GitHub/tool-dapploy-nodejs/dapploy:26:21)
    at execute.forEach (/Users/arietrouw/GitHub/tool-dapploy-nodejs/dapploy:46:13)
    at Array.forEach (<anonymous>)
    at /Users/arietrouw/GitHub/tool-dapploy-nodejs/dapploy:44:11
    at Object.<anonymous> (/Users/arietrouw/GitHub/tool-dapploy-nodejs/dapploy:53:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)

**Comment by klivin** [comment]
Now we support empty config
